Lambda-School-Labs/property-manager-fe

- src/App.js
- src/index.js
- src/scss/index.scss
- src/views/LandingPage.js
This PR contains some scaffolding and App component level changes so it should probably be merged in ASAP and pulled down to avoid merge conflicts
-Added views folder
-Added landing page view component
-Created landing page scss partial and imported into index.scss
-imported index.scss into root index.js
> added LandingPage view, brought in sass styles from index.scss

- src/App.js
- src/components/SignUpForm/SignUp.js
> sign up form is developed

- src/components/UI/index.js
- src/scss/_Dashboard.scss
- src/views/Dashboard.js
Revealed content hidden by sidenav
> SideNav UI component adjusted

- src/components/LoginForm/Form.js
- src/components/UI/index.js
- src/scss/_global.scss
- src/scss/_variables.scss
- src/scss/index.scss
This PR organizes and cleans up some styling, abstracts some styling into global sass styles, consolidated and removed duplicate styled components and overhauled the login styles.
> Style updates

- src/components/SignUpForm/SignUp.js
> Teddy zenebe

- src/components/SignUpForm/SignUp.js
> error icon is added and the updated Formcard is used

- src/App.js
- src/components/SignUpForm/SignUp.js
- src/components/navigation.js
- src/index.js
- src/store/actions/index.js
- src/store/index.js
- src/store/reducers/index.js
- src/views/SignUp.js
This adds a redux flow for authentication on the front end.
> All of the signup and login flow

- public/index.html
- src/views/Contact.js
- src/views/Features.js
- src/views/index.js
> contact form

- src/components/UI/index.js
- src/components/navigation.js
- src/scss/index.scss
- ~/.git-templates/git-secrets/hooks/commit-msg
- ~/.git-templates/git-secrets/hooks/pre-commit
- ~/.git-templates/git-secrets/hooks/prepare-commit-msg
> mobile and tablet menus

- .gitignore
- netlify.toml
- package-lock.json
> netlify changes

- src/__test__/component/AddProperty.test.js
- src/components/AddPropertyForm/AddPropertyForm.js
- src/components/LoginForm/LoginForm.js
- src/components/UI/index.js
- src/scss/_global.scss
- src/store/actions/index.js
- src/store/reducers/authReducer.js
- src/store/reducers/index.js
- src/store/reducers/propReducer.js
- src/views/Dashboard.js
Created add property actions and split the reducer logic into authReducer and propReducer (properties), hooked up the add a property form to the back-end with redux.
> Hookup prop form

- src/components/Auth/LoginForm/LoginForm.js
- src/components/UI/index.js
> fixed a bug

- src/components/Auth/AuthFlip.js
- src/components/Auth/LoginForm/LoginForm.js
- src/components/Auth/SignUpForm/SignUp.js
- src/components/UI/index.js
- src/scss/_animation.scss
- src/scss/components/_forms.scss
- src/scss/index.scss
CSS Animation quick fix for the Auth Flip
> Tyler Turnipseed

- src/components/Auth/Routes/ProtectedRoutes.js
- src/components/Auth/SignUpForm/SignUp.js
- src/components/UI/FloatingActions.js
- src/components/WorkorderForm/LandlordWorkOrderForm.js
- src/components/WorkorderForm/TenantWorkOrderForm.js
- src/components/WorkorderForm/WorkOrderForm.js
- src/scss/components/_forms.scss
- src/views/tenantDashboard/TenantDashboard.js
Adds type selection to sign up form.
Height of form needs adjustment now :(
> Tenant sign up

- src/components/Auth/Routes/ProtectedRoutes.js
- src/components/UI/FloatingActions.js
- src/components/WorkorderForm/LandlordWorkOrderForm.js
- src/components/WorkorderForm/TenantWorkOrderForm.js
- src/components/WorkorderForm/WorkOrderForm.js
- src/views/tenantDashboard/TenantDashboard.js
Basic work order form for tenants set up
Also copied into what will be the landlord work order form
Work order form hooked up to floating action button
Better implementation to come
Still waiting for endpoint on the backend for full functionality
> Work order logic

- src/components/WorkOrderForm/WorkOrderForm.js
- src/store/actions/index.js
- src/store/reducers/propReducer.js
- src/views/dashboard/profile/ProfileCard.js
- src/views/dashboard/properties/Property.js
- src/views/dashboard/tenants/CreateTenant.js
- src/views/dashboard/tenants/Tenants.js
> removed console logs

- src/components/UI/FloatingActions.js
- src/views/landing/Features.js
Adds paths to 2 landloard floating action buttons
Adds user profile button for tenants
> Floating ACTION Pathing

- src/views/dashboard/tenants/CreateTenant.js
> tenant now also gets tenants so there is some sort of feedback. Kappa

- src/scss/views/landing/_Home.scss
- src/views/landing/Header/index.js
- src/views/landing/LandingPage.js
Description
Styled header on the landing page
When the header component was added to the landing page the style didn't match the figma design
Type of change
Styling
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
Change Status
Complete, tested, ready to review and merge
Complete, but not tested (may need new tests)
Incomplete/work-in-progress, PR is for discussion/feedback
How Has This Been Tested?
Test A
Test B
Checklist
My code follows the style guidelines of this project
I have performed a self-review of my own code
My code …
> fixed header styling on landing page

- src/scss/views/landing/_Home.scss
Made minor changes to the marketing page header to better match the figma mock up
Styling slightly off
Styling
> minor changes to header styling

- src/components/Tenants/TenantForm.js
- src/components/WorkOrderForm/WorkOrderForm.js
- src/helpers/utils.js
- src/views/dashboard/properties/Property.js
- src/views/tenantDashboard/TenantProperty.js
Created utils file in the helpers folder, moved styling object from tenantform and workorderform
to utils file to make code more DRY
Duplicate Code
Refactor
> moved duplicate code to utils.js

- src/components/Navigation/navigation.js
App crashing because of useEffect changing bg color on nav
- not tested
> remove useEffect

- package-lock.json
- src/App.js
- src/components/Auth/LoginForm/LoginForm.js
- src/components/Auth/SignUpForm/SignUp.js
- src/components/Navigation/navigation.js
- src/store/actions/index.js
- src/views/onBoarding/onBoarding.js
- Refactored onboarding feature from modal-flip to onboarding page. Still needs styling.
> Refactored onboarding

- src/components/ContactForm/ContactForm.js
- src/scss/components/_forms.scss
- src/scss/views/landing/_Contact.scss
- src/views/landing/Contact.js
Created media queries for the contact page
Contact form styling wasn't mobile friendly
Styling
- [ x] Complete, tested, ready to review and merge
> styled contact page mobile views

- src/components/Auth/LoginForm/LoginForm.js
Fixes # syntax error blocking rendering
Syntax error fix
> fixed syntax error blocking rendering

- src/components/ContactForm/ContactForm.js
- src/scss/components/_forms.scss
- src/scss/views/landing/_Contact.scss
- src/views/landing/Contact.js
Fixed media queries to make the contact form responsive to different screen sizes
The form wasn't styled correctly in all the different screen sizes
Styling
> made contact form responsive

- src/components/Navigation/navigation.js
- src/scss/_global.scss
- src/scss/components/_nav.scss
- src/views/landing/Footer/Footer.js
- src/views/landing/Footer/footer.scss
Fixes issue where nav links wont link to proper section when on any other view besides the landing view.
Fixes responsive layout issues in top and footer navs.
> update nav links and responsiveness

- src/components/Auth/LoginForm/LoginForm.js
- src/components/Auth/SignUpForm/SignUp.js
- src/scss/components/_onboardingForms.scss
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Complete, tested, ready to review and merge
N/A
> Fixed styling issue from conflict

- src/scss/_global.scss
- src/views/landing/Footer/footer.scss
> ensure footer always @ bottom of screen

- src/store/actions/index.js
Removed the slash after api to fix the routing issues.
Bug fix to hit the proper backend.
Type fix.
- [X  ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Complete, tested, ready to review and merge
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My changes generate no new warnings
- [ X ] New and existing unit tests pass locally with my changes
- [ X ] There are no merge conflicts
> Updated the baseUrl (GH autogenerated my branch name)

- src/scss/components/_onboardingForms.scss
- src/scss/views/landing/_Features.scss
- src/views/landing/Features/features.scss
- [ X ] Complete, tested, ready to review and merge
- N/A
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My changes generate no new warnings
> Changed styling on features list

- README.md
- src/scss/components/_onboardingForms.scss
- src/scss/views/landing/_Contact.scss
- src/scss/views/landing/_Features.scss
- src/views/landing/Features/features.scss
Style changes being migrated into Master
No fixes
Style
- [X ] New feature (non-breaking change which adds functionality)
- [  X] Complete, tested, ready to review and merge
- [ X ] My code has been reviewed by at least one peer
> Moving Cole's changes into Master

- src/views/dashboard/tenants/CreateTenant.js
Added an or statement when creating a tenant to check the URL. It was hard coded for local testing.
> Added an or statement to check the current url in tenants.

- src/views/dashboard/tenants/CreateTenant.js
Hard coded the url for creating for now.
> Hard coded the url for now. Will need changed.

- .codeclimate.yml
Adds a configuration file for Code Climate.
> Added CodeClimate Config

- package.json
Quick package change.
Error for testing
Error fix
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Complete, tested, ready to review and merge
> Changed the test script to watch = false

- src/components/Tenants/TenantCard.js
- src/views/dashboard/properties/Property.js
- src/views/dashboard/tenants/Tenant.js
- [ ✔️ ] Bug fix (non-breaking change which fixes an issue)
- [ ✔️ ] New feature (non-breaking change which adds functionality)
- [ ✔️ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ✔️ ] This change requires a documentation update
- [  ] Complete, tested, ready to review and merge
- [ ✔️ ] Complete, but not tested (may need new tests)
- [ ✔️ ] My code follows the style guidelines of this project
- [ ✔️ ] I have performed a self-review of my own code
- [ ✔️ ] My code has been reviewed by at least one peer
- [  ✔️] I have commented my code, particularly in hard-to-understand areas
- [ ✔️ ] I have made corresponding changes to the documentation
- [  ✔️] My changes generate no …
> Updated propertylist items, display name
